### ISSUE TITLE
Task1

### ISSUE THREAD

**Issue by YakutovDmitriy** [romanovamar/bio-python#1]
Implementations of `unique`, `transposeDict` and `mex` functions are ok.

`frequencyDict` has a bug. Did you test it?

**Comment by romanovamar** [comment]
frequencyDict=lambda s: {i:s.count(i) for i in s}

**Comment by YakutovDmitriy** [comment]
:+1: 
Please commit this change to master

**Comment by romanovamar** [comment]
Done.

**Comment by YakutovDmitriy** [comment]
Ok!
