### ISSUE TITLE
task2

### ISSUE THREAD

**Issue by YakutovDmitriy** [romanovamar/bio-python#2]
Hi!

Functions `listToString` `addBorder`, `shorting`, `competition` and `makeShell` are ok!

Function and `goodPairs` have some issues. Please fix them.

Also you are to fix your hw1 to satisfy pep and write tests for functions from hw1.

**Comment by romanovamar** [comment]
Done.

**Comment by YakutovDmitriy** [comment]
Everything is ok except the function `unique` from hw1.
You have an assertion: `assert len(e) == 0, 'Empty list'`. It is pretty strange.

**Comment by YakutovDmitriy** [comment]
Also it is not the best way to design function `mex`.
Someone who uses your implementation is able to call this function with argument `i='abacaba'`, etc. He will get an error in such case. You can implement your idea using the following approach:

```python
def mex(e):
    def func(e, i):
        return i if i not in e else func(e, i + 1)  
    assert type(e) == list, 'Wrong type'
    return func(e, 1)
```
